project:
  type: website
  output-dir: docs

website:
  # page-footer:
  #   border: true 
  #   left: "Copyright 2024, A. Setiono"
  #   right: 
  #     - icon: twitter
  #       # href: https://twitter.com/setiono_andrew
  #     - icon: github
  #       href: https://github.com/andrewse98/personal-web
  favicon: img/favicon.ico
  navbar:
    logo: img/web_logo.png  
    left:
      - text: "about"
        file: about.qmd
      - text: "blog"
        file: index.qmd

format:
  html:
    theme: 
    - yeti
    - custom.scss
    mainfont: Helvetica Neue 
    monofont: Consolas
    toc: true
